name: Oasis CD

on:
  push:
    branches: [prod]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /srv/static/oasis/2024/oasis-2024-web
            sudo git pull origin prod
            git status
            npm install
            sudo npm run build
